print('calcule a o tempo em que um carro leva para chegar em um determinado lugar')
dist = input('digite a distância em KM ')
velo = input('digite a velocidade aproximada em que o carro percorreu o percuso ')
tempo = float(dist) / float(velo)
print('O tempo extimado para o percuso é de:', tempo, "horas")